/**
 * Backend RESTful API Interface
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ObjectId } from './objectId';
import {UserPublicProfile} from "./userPublicProfile";

export interface Comment { 
    commentId: ObjectId;
    author: UserPublicProfile;
    body: string;
    postedAt: string;
    repliesCount: number;
    likesCount: number;
    replyId?: ObjectId;
}
